name: build-test-dotnet

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'Application/**'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'Application/**'

env:
  registryName: "vz2zwcq6pu34owthreg.azurecr.io"
  repositoryName: "wth/dotnetcoreapp"
  dockerFolderPath: "Application/src/RazorPagesTestSample"
  tag: ${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj

    - name: Build
      run: dotnet build --no-restore ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj

    - name: Test
      run: dotnet test --no-build --verbosity normal ./Application/tests/RazorPagesTestSample.Tests/RazorPagesTestSample.Tests.csproj

  dockerize:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker login
        run: docker login $registryName -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}

      - name: Docker build
        run: docker build -t $registryName/$repositoryName:$tag --build-arg build_version=$tag $dockerFolderPath

      - name: Docker push
        run: docker push $registryName/$repositoryName:$tag
  
  release:
    needs: dockerize
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, test, prod]
    steps:
      - name: az login
        run: az login --service-principal --username ${{ secrets.CLIENT_ID }}  --password ${{ secrets.CLIENT_SECRET }}  --tenant ${{ secrets.TENANT_ID }} 
      
      - uses: trstringer/manual-approval@v1
        if: ${{ matrix.environment }} == 'test' || ${{ matrix.environment }} == 'prod'
        with:
          secret: ${{ github.TOKEN }}
          approvers: davejg10
          minimum-approvals: 1
          issue-title: "Deploying v${{ env.registryName }}/${{ env.repositoryName }}:${{ env.tag }} to ${{ matrix.environment }}"
          issue-body: "Please approve or deny the deployment."
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''

      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'vz2zwcq6pu34o-${{ matrix.environment }}'
          images: ${{ env.registryName }}/${{ env.repositoryName }}:${{ env.tag }}

      
            