name: deploy-workflow
run-name: Deploy workflow

on:
  workflow_dispatch:
    inputs:
        env:
          type: choice
          description: Environment
          options: 
          - dev
          - test
          - prod


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: az login
        run: az login --service-principal --username ${{ secrets.CLIENT_ID }}  --password ${{ secrets.CLIENT_SECRET }}  --tenant ${{ secrets.TENANT_ID }} 

      - uses: azure/arm-deploy@v2
        with:
          resourceGroupName: ${{ vars.RG_NAME }}
          template: ./InfrastructureAsCode/main.bicep
          parameters: environment=${{ github.event.inputs.env }}
